### ISSUE TITLE
Problem with value read

### ISSUE THREAD

**Issue by s-triar** [THP-JOE/Python_SI1145#13]
Hi, I m using SI1145 exactly like the tutorial. but the sensor always shows 260, 254, 0.01 for Vis, Ir, and UV index respectively although I give it a flashlight and keep it in a dark place. Is this need calibration or is my sensor broken?

**Comment by Bra1nsen** [comment]
same - did you solve the problem?

**Comment by s-triar** [comment]
it was my fault. sorry. the flash light I used back then did not have enough energy maybe it is my smartphone flash light. When I used emergency lamp with shape tube, the value increased. Moreover when the sensor is under direct sunlight, the value increased higher.
